[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "Bw8r7WDzZcxR4HPdgQDB3CLo7piCNipdtAeBdHzw9TcK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
